version: '3.9'

services:
  cinelsd-redis:
    image: redis:7.2-rc1-alpine3.18
    container_name: cinelsd-redis
    restart: ${REDIS_RESTART_POLICY:-no}
    networks:
      - cinelsd
    volumes:
      - ./transformer/data/normalized:/data
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 5s
      timeout: 5s
      retries: 15

  cinelsd-server-go:
    image: cinelsd-server-go:latest
    build:
      context: ./server-go
    container_name: cinelsd-server-go
    restart: ${SERVER_RESTART_POLICY:-no}
    environment:
      PORT: 8001
      REDIS_HOST: cinelsd-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_MOVIE_DATABASE: 1
      REDIS_MOVIE_MAIN_ACTORS_DATABASE: 2
      REDIS_ACTOR_DATABASE: 3
      GOGC: ${SERVER_GOGC:-100}
      GOMEMLIMIT: ${SERVER_GOMEMLIMIT:-500MiB}
      GOMAXPROCS: ${SERVER_GOMAXPROCS:-1}
    ports:
      - 8001:8001
    networks:
      - cinelsd
    depends_on:
      cinelsd-redis:
        condition: service_healthy
    healthcheck:
      test: lsof -i:$$PORT
      interval: 2s
      timeout: 2s
      retries: 10

  cinelsd-server-node:
    image: cinelsd-server-node:latest
    build:
      context: ./server-node
    container_name: cinelsd-server-node
    restart: ${SERVER_RESTART_POLICY:-no}
    environment:
      PORT: 8002
      REDIS_HOST: cinelsd-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_MOVIE_DATABASE: 1
      REDIS_MOVIE_MAIN_ACTORS_DATABASE: 2
      REDIS_ACTOR_DATABASE: 3
      SERVER_INSTANCES: ${SERVER_INSTANCES:-1}
    ports:
      - 8002:8002
    networks:
      - cinelsd
    depends_on:
      cinelsd-redis:
        condition: service_healthy
    healthcheck:
      test: lsof -i:$$PORT
      interval: 2s
      timeout: 2s
      retries: 10

  cinelsd-server-node-replicas:
    image: cinelsd-server-node:latest
    build:
      context: ./server-node
    environment:
      PORT: 8001
      REDIS_HOST: cinelsd-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_MOVIE_DATABASE: 1
      REDIS_MOVIE_MAIN_ACTORS_DATABASE: 2
      REDIS_ACTOR_DATABASE: 3
    networks:
      - cinelsd
    deploy:
      replicas: 1
      restart_policy:
        condition: ${SERVER_RESTART_POLICY:-no}
    depends_on:
      cinelsd-redis:
        condition: service_healthy
    healthcheck:
      test: lsof -i:$$PORT
      interval: 2s
      timeout: 2s
      retries: 10

  cinelsd-server-node-replicas-nginx:
    image: nginx:1.25.0-alpine3.17
    container_name: cinelsd-server-node-nginx
    ports:
      - 8000:8000
    networks:
      - cinelsd
    volumes:
      - ./server-node/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      cinelsd-server-node:
        condition: service_healthy
    healthcheck:
      test: lsof -i:8000
      interval: 2s
      timeout: 2s
      retries: 10

networks:
  cinelsd:
    driver: bridge
