version: '3.9'

services:
  cinelsd-redis:
    image: redis:7.2-rc1-alpine3.18
    container_name: cinelsd-redis
    restart: ${REDIS_RESTART_POLICY:-no}
    networks:
      - cinelsd
    volumes:
      - ./transformer/data/normalized:/data
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping | grep PONG
      interval: 5s
      timeout: 5s
      retries: 15

  cinelsd-server:
    image: cinelsd-server:latest
    build:
      context: ./server
    container_name: cinelsd-server
    restart: ${SERVER_RESTART_POLICY:-no}
    environment:
      PORT: 8001
      REDIS_HOST: cinelsd-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_MOVIE_DATABASE: 1
      REDIS_MOVIE_MAIN_ACTORS_DATABASE: 2
      REDIS_ACTOR_DATABASE: 3
    ports:
      - 8001:8001
    networks:
      - cinelsd
    depends_on:
      cinelsd-redis:
        condition: service_healthy
    healthcheck:
      test: lsof -i:$$PORT
      interval: 2s
      timeout: 2s
      retries: 10

networks:
  cinelsd:
    driver: bridge
